node:
  url: "/node"
  policy: "node.xml"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
hi:
  url: "/hi"
  policy: "hi.xml"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
